## 1. SMS Data Exploration

SMS data is available as CSV file along with class material. In the code below, we are copying the from Google drive.

In [ ]:
from google.colab import files
uploaded = files.upload()

Saving sms (1).tsv to sms (1) (2).tsv

In [ ]:
from google.colab import drive
drive.mount('/gdrive')

Drive already mounted at /gdrive; to attempt to forcibly remount, call drive.mount("/gdrive", force_remount=True).

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
sms_df=pd.read_table('sms (1).tsv', header=None, names=['label','message'])

In [ ]:
# read file into pandas using a relative path. Please change the path as needed
sms_df = pd.read_table('/gdrive/MyDrive/HGN/NLP By HGN/NLP for SRM /HGN/Unit1/sms.tsv', header=None, names=['label', 'message'])

In [ ]:
#Total number of SMS
sms_df.shape

(5572, 2)

In [ ]:
#checking contents of dataframe
sms_df.sample(n=15)

     label                                            message
1049   ham  I walked an hour 2 c u! doesnt that show I ca...
1553   ham                                           U too...
426    ham                          Ok. She'll be ok. I guess
1351   ham                             Bugis oso near wat...
5236   ham  Your opinion about me? 1. Over 2. Jada 3. Kusr...
4529   ham  HOW ARE U? I HAVE MISSED U! I HAVENT BEEN UP 2...
3649   ham  As per your request 'Maangalyam (Alaipayuthe)'...
2756   ham                              We r outside already.
4135   ham  Is it your yahoo boys that bring in the perf? ...
1299   ham       Your daily text from me – a favour this time
1966   ham  Thanks. It was only from tescos but quite nice...
5321   ham  Ok no problem... Yup i'm going to sch at 4 if ...
3094   ham  staff.science.nus.edu.sg/~phyhcmk/teaching/pc1323
3019   ham       I didn't get the second half of that message
4196  spam  Double mins and txts 4 6months FREE Bluetooth ...

In [ ]:
sms_df.tail(10)

     label                                            message
5562   ham  Ok lor... Sony ericsson salesman... I ask shuh...
5563   ham                                Ard 6 like dat lor.
5564   ham  Why don't you wait 'til at least wednesday to ...
5565   ham                                       Huh y lei...
5566  spam  REMINDER FROM O2: To get 2.50 pounds free call...
5567  spam  This is the 2nd time we have tried 2 contact u...
5568   ham               Will ü b going to esplanade fr home?
5569   ham  Pity, * was in mood for that. So...any other s...
5570   ham  The guy did some bitching but I acted like i'd...
5571   ham                         Rofl. Its true to its name

In [ ]:
sms_df.loc[0, 'message']

'Go until jurong point, crazy.. Available only in bugis n great world la e buffet... Cine there got amore wat...'

In [ ]:
#Spam vs ham
sms_df.groupby('label').count()

       message
label
ham       4825
spam       747

In [ ]:
4825/(4825+747)

0.8659368269921034

In [ ]:
#Check out SMS messages which is legitimate - ham
msg_num = np.random.randint(0, sms_df.shape[0])
print(sms_df.loc[msg_num, 'label'], ':', sms_df.loc[msg_num, 'message'])

ham : K fyi x has a ride early tomorrow morning but he's crashing at our place tonight

In [ ]:
#Check out SMS messages which is a SPAM
print(sms_df.loc[1734, 'label'], ':', sms_df.loc[1732, 'message'])

spam : Lol. Well quality aint bad at all so i aint complaining

In [ ]:
#Checkout missing values
sms_df.isnull().sum()

label      0
message    0
dtype: int64

In [ ]:
# convert label to a numerical variable
sms_df['label_num'] = sms_df.label.map({'ham':0, 'spam':1})

In [ ]:
#We should have label_num column in dataframe
sms_df.sample(n=15)

     label                                            message  label_num
4723   ham  I'm home, my love ... If your still awake ... ...          0
593   spam  PRIVATE! Your 2003 Account Statement for 07753...          1
2720   ham     Go where n buy? Juz buy when we get there lar.          0
3111  spam  Good Luck! Draw takes place 28th Feb 06. Good ...          1
4121   ham  Babe! How goes that day ? What are you up to ?...          0
1683   ham  HI BABE U R MOST LIKELY TO BE IN BED BUT IM SO...          0
1946   ham  Can ü call me at 10:10 to make sure dat i've w...          0
1176   ham  Horrible u eat macs eat until u forgot abt me ...          0
3045   ham  Let me know how it changes in the next 6hrs. I...          0
2288   ham  Alex knows a guy who sells mids but he's down ...          0
204    ham                           Goodmorning sleeping ga.          0
4987   ham                   That's y u haf 2 keep me busy...          0
4339   ham                        Yes when is the appt again?          0
3116   ham                   I wait 4 ü inside da car park...          0
383    ham         Hey leave it. not a big deal:-) take care.          0

## 2. Create Training & Test Dataset

In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
# split X and y into training and testing sets
sms_train, sms_test, y_train, y_test = train_test_split(sms_df.message,
                                                        sms_df.label_num,
                                                        random_state=2)

In [ ]:
sms_train.reset_index(inplace=True, drop=True)
sms_test.reset_index(inplace=True, drop=True)
y_train.reset_index(inplace=True, drop=True)
y_test.reset_index(inplace=True, drop=True)

In [ ]:
#Traing data
print(sms_train.shape)
print(y_train.shape)

(4179,)
(4179,)

In [ ]:
#Test Data
print(sms_test.shape)
print(y_test.shape)

(1393,)
(1393,)

## 3. Tokenization & Vectorization

Using **CountVectorizer**, to get numeric features.

In [ ]:
# import and instantiate CountVectorizer (with the default parameters)
from sklearn.feature_extraction.text import CountVectorizer
cvect = CountVectorizer(min_df=3)

In [ ]:
sms_train.head()

0    Ok I'm gonna head up to usf in like fifteen mi...
1     That's a shame! Maybe cld meet for few hrs tomo?
2    Will do. Was exhausted on train this morning. ...
3    I will be gentle princess! We will make sweet ...
4    I know a few people I can hit up and fuck to t...
Name: message, dtype: object

In [ ]:
#Feed SMS data to CountVectorizer
cvect.fit(sms_train)

CountVectorizer(min_df=3)

In [ ]:
#Check the vocablury size
len(cvect.vocabulary_)

2348

In [ ]:
#What is there in the vocabulary
cvect.vocabulary_

{'ok': 4703,
 'gonna': 3055,
 'head': 3219,
 'up': 6914,
 'to': 6669,
 'usf': 6950,
 'in': 3493,
 'like': 3930,
 'fifteen': 2729,
 'minutes': 4301,
 'that': 6550,
 'shame': 5820,
 'maybe': 4205,
 'cld': 1762,
 'meet': 4230,
 'for': 2827,
 'few': 2718,
 'hrs': 3384,
 'tomo': 6693,
 'will': 7235,
 'do': 2283,
 'was': 7110,
 'exhausted': 2602,
 'on': 4722,
 'train': 6746,
 'this': 6590,
 'morning': 4387,
 'too': 6709,
 'much': 4430,
 'wine': 7244,
 'and': 920,
 'pie': 4983,
 'you': 7410,
 'sleep': 5975,
 'well': 7171,
 'be': 1224,
 'gentle': 2984,
 'princess': 5185,
 'we': 7133,
 'make': 4137,
 'sweet': 6400,
 'love': 4043,
 'know': 3786,
 'people': 4924,
 'can': 1576,
 'hit': 3294,
 'fuck': 2913,
 'the': 6553,
 'yes': 7394,
 'dear': 2105,
 'call': 1552,
 'tmorrow': 6663,
 'pls': 5032,
 'accomodate': 752,
 'said': 5635,
 'text': 6526,
 'him': 3286,
 'one': 4727,
 'more': 4383,
 'time': 6636,
 'sms': 6019,
 'services': 5787,
 'your': 7416,
 'inclusive': 3501,
 'credits': 1990,
 'gotto': 3078,
 'www': 7349,
 'comuk': 1872,
 'net': 4537,
 'login': 3998,
 '3qxj9': 450,
 'unsubscribe': 6909,
 'with': 7261,
 'stop': 6246,
 'no': 4585,
 'extra': 2631,
 'charge': 1670,
 'help': 3250,
 '08702840625': 79,
 '220cm2': 344,
 '9ae': 708,
 'two': 6825,
 'teams': 6479,
 'waiting': 7079,
 'some': 6053,
 'players': 5018,
 'alrite': 886,
 'sam': 5645,
 'its': 3609,
 'nic': 4563,
 'just': 3710,
 'checkin': 1694,
 'is': 3591,
 'ur': 6929,
 'number': 4645,
 'so': 6039,
 'it': 3603,
 'my': 4462,
 'hope': 3340,
 'not': 4619,
 'doing': 2304,
 'anything': 958,
 'drastic': 2345,
 'don': 2314,
 'dare': 2075,
 'sell': 5758,
 'pc': 4910,
 'or': 4759,
 'phone': 4964,
 'todays': 6677,
 'voda': 7039,
 'numbers': 4646,
 'ending': 2480,
 '1225': 267,
 'are': 1006,
 'selected': 5752,
 'receive': 5389,
 '50award': 518,
 'if': 3451,
 'have': 3208,
 'match': 4184,
 'please': 5024,
 '08712300220': 95,
 'quoting': 5310,
 'claim': 1750,
 'code': 1809,
 '3100': 422,
 'standard': 6191,
 'rates': 5342,
 'app': 975,
 'now': 4631,
 'only': 4733,
 'took': 6710,
 'tablets': 6424,
 'reaction': 5362,
 'what': 7191,
 'did': 2209,
 'bank': 1172,
 'say': 5679,
 'about': 730,
 'money': 4371,
 'wat': 7116,
 'liao': 3909,
 'where': 7201,
 'still': 6234,
 'got': 3072,
 'good': 3057,
 'lets': 3904,
 'thank': 6543,
 'god': 3039,
 'complete': 1859,
 'drug': 2370,
 'lots': 4032,
 'of': 4679,
 'water': 7123,
 'beautiful': 1229,
 'day': 2093,
 'am': 895,
 'at': 1070,
 'gas': 2958,
 'station': 6209,
 'go': 3033,
 'there': 6570,
 'ooh': 4738,
 '4got': 501,
 'start': 6199,
 'belly': 1267,
 'dancing': 2071,
 'moseley': 4390,
 'weds': 7152,
 '30': 408,
 'want': 7098,
 'join': 3676,
 'me': 4212,
 'they': 6576,
 'cafe': 1544,
 'yay': 7381,
 'finally': 2746,
 'lol': 4002,
 'missed': 4312,
 'our': 4792,
 'cinema': 1746,
 'trip': 6773,
 'last': 3842,
 'week': 7155,
 'mm': 4330,
 'ask': 1047,
 'come': 1833,
 'enough': 2499,
 'really': 5374,
 'dun': 2392,
 'bluff': 1358,
 'leh': 3889,
 'early': 2408,
 'nite': 4582,
 'message': 4259,
 'from': 2904,
 'truro': 6788,
 'hospital': 3354,
 'ext': 2629,
 'here': 3262,
 'as': 1040,
 'by': 1539,
 'side': 5912,
 'wake': 7080,
 'already': 884,
 'picking': 4978,
 'us': 6943,
 'later': 3848,
 'rite': 5552,
 'taking': 6439,
 'sq825': 6176,
 'reaching': 5360,
 'ard': 1005,
 'smth': 6024,
 'dat': 2084,
 'check': 1691,
 'arrival': 1031,
 'ya': 7371,
 'soon': 6078,
 'dont': 2318,
 'exactly': 2586,
 'could': 1952,
 'chechi': 1690,
 'dunno': 2394,
 'get': 2994,
 'her': 3261,
 'around': 1026,
 'use': 6947,
 'half': 3160,
 '8th': 696,
 'should': 5880,
 'buy': 1529,
 'blackberry': 1326,
 'bold': 1368,
 'torch': 6724,
 'new': 4551,
 'used': 6948,
 'let': 3903,
 'plus': 5037,
 'saying': 5682,
 'lt': 4067,
 'gt': 3124,
 'wifi': 7228,
 'ipad': 3579,
 'll': 3978,
 'all': 874,
 'creepy': 1992,
 'he': 3218,
 'won': 7288,
 'think': 6582,
 'forgot': 2839,
 'cause': 1628,
 'yelling': 7387,
 'scrappy': 5708,
 'miss': 4310,
 'wait': 7076,
 'home': 3324,
 'lonely': 4007,
 'today': 6676,
 'pookie': 5080,
 'didn': 2211,
 'voicemail': 7043,
 '08719181513': 147,
 'she': 5833,
 'find': 2749,
 'sent': 5775,
 'an': 916,
 'offline': 4692,
 'how': 3371,
 'anjola': 928,
 'ooooooh': 4740,
 'tell': 6494,
 'yoville': 7424,
 'eastenders': 2414,
 'tv': 6816,
 'quiz': 5307,
 'flower': 2797,
 'does': 2293,
 'dot': 2327,
 'compare': 1852,
 'herself': 3266,
 'violet': 7023,
 'tulip': 6806,
 'lily': 3935,
 'txt': 6827,
 '84025': 651,
 'chance': 1658,
 'win': 7238,
 '100': 240,
 'cash': 1617,
 'wkent': 7271,
 '150p16': 290,
 'tough': 6735,
 'but': 1525,
 'italian': 3604,
 'food': 2821,
 'pretty': 5174,
 'dress': 2351,
 'panties': 4850,
 'office': 4688,
 'pm': 5040,
 'going': 3045,
 'anyway': 961,
 'holla': 3320,
 'whenever': 7198,
 're': 5357,
 'because': 1232,
 'need': 4520,
 'excuse': 2594,
 'creep': 1991,
 'sarasota': 5657,
 'tomarrow': 6690,
 'court': 1962,
 'decimal': 2117,
 'bus': 1519,
 'stand': 6190,
 'send': 5766,
 'min': 4283,
 'thanx': 6548,
 'lot': 4030,
 'cute': 2047,
 'thought': 6600,
 'friendship': 2892,
 'necessary': 4516,
 'share': 5826,
 'every': 2559,
 'secret': 5730,
 'close': 1775,
 'frnd': 2897,
 'watever': 7124,
 'shared': 5827,
 'true': 6785,
 'sorry': 6087,
 'ever': 2558,
 'angry': 924,
 'misbehaved': 4306,
 'hurt': 3410,
 'plz': 5039,
 'slap': 5973,
 'urself': 6942,
 'bcoz': 1219,
 'fault': 2688,
 'basically': 1192,
 'oh': 4698,
 'google': 3067,
 'nearby': 4511,
 'cliffs': 1772,
 'meeting': 4232,
 'then': 6565,
 'lor': 4022,
 'feel': 2704,
 'comin': 1838,
 'keep': 3740,
 'payasam': 4901,
 'rinu': 5548,
 'brings': 1466,
 'jus': 3709,
 'telling': 6495,
 'leaving': 3880,
 'shanghai': 5822,
 '21st': 341,
 'instead': 3545,
 'haf': 3152,
 'cya': 2055,
 'sir': 5942,
 'salam': 5638,
 'alaikkum': 857,
 'pride': 5180,
 'pleasure': 5027,
 'tea': 6473,
 'shop': 5867,
 'pleased': 5025,
 'contact': 1906,
 'qatar': 5289,
 'rakhesh': 5328,
 'indian': 3512,
 'save': 5674,
 'respectful': 5497,
 'regards': 5429,
 'coming': 1839,
 'dinner': 2236,
 'thanks': 6544,
 'bomb': 1372,
 'date': 2086,
 'wanted': 7100,
 'usually': 6956,
 'take': 6434,
 'fucking': 2916,
 'respond': 5499,
 'question': 5297,
 'leave': 3878,
 'rct': 5352,
 'thnq': 6594,
 'adrian': 797,
 'rgds': 5531,
 'vatian': 6982,
 '000': 1,
 'prize': 5195,
 'call09050000327': 1553,
 'rstm': 5591,
 'sw7': 6389,
 '3ss': 452,
 '150ppm': 293,
 'somewhr': 6068,
 'someone': 6057,
 'surely': 6374,
 'made': 4115,
 'has': 3196,
 'decided': 2115,
 'perfect': 4928,
 'person': 4942,
 'till': 6634,
 'den': 2155,
 'enjoy': 2492,
 'crushes': 2008,
 'hi': 3275,
 'both': 1398,
 'would': 7322,
 'hasn': 3198,
 'seen': 5747,
 'down': 2332,
 'gently': 2986,
 'back': 1146,
 'work': 7304,
 '2morro': 384,
 'term': 6511,
 'over': 4812,
 '2nite': 392,
 'sexy': 5802,
 'passion': 4885,
 'b4': 1135,
 'chat': 1682,
 '09099726481': 232,
 'luv': 4081,
 'dena': 2156,
 'calls': 1567,
 'minmobsmorelkpobox177hp51fl': 4293,
 'pa': 4832,
 'knw': 3790,
 'who': 7212,
 'ru': 5595,
 'way': 7130,
 'stay': 6210,
 'bothering': 1400,
 'trust': 6789,
 'answers': 944,
 'out': 4794,
 'class': 1758,
 'hours': 3366,
 'vivek': 7037,
 'complimentary': 1865,
 'star': 6194,
 'ibiza': 3428,
 'holiday': 3319,
 '10': 239,
 'needs': 4525,
 'urgent': 6933,
 'collection': 1822,
 '09066364349': 211,
 'landline': 3828,
 'lose': 4024,
 'box434sk38wp150ppm18': 1420,
 'care': 1597,
 'nyc': 4659,
 'audiitions': 1094,
 'trying': 6792,
 'relocate': 5443,
 'moby': 4352,
 'pub': 5261,
 'high': 3280,
 'street': 6265,
 'duchess': 2383,
 'cornwall': 1934,
 'first': 2765,
 'name': 4479,
 '82277': 634,
 'unsub': 6908,
 '50': 515,
 '008704050406': 3,
 'sp': 6107,
 'questions': 5299,
 'mistake': 4319,
 'repeat': 5470,
 'instructions': 3547,
 'again': 822,
 'road': 5554,
 'house': 3367,
 '2nd': 389,
 'tried': 6772,
 '1450': 282,
 '09053750005': 163,
 '310303': 423,
 'cs': 2011,
 '08718725756': 132,
 '140ppm': 280,
 'wonder': 7290,
 'roger': 5564,
 'cl': 1749,
 'babes': 1141,
 'had': 3151,
 'shit': 5854,
 'nights': 4574,
 'fell': 2710,
 'asleep': 1054,
 'knackered': 3780,
 'dreading': 2348,
 'tonight': 6704,
 'thou': 6598,
 'upto': 6928,
 'babe': 1140,
 'lost': 4029,
 'try': 6791,
 'rebooting': 5384,
 'oi': 4699,
 'when': 7197,
 'ring': 5542,
 'yup': 7436,
 'giving': 3022,
 'problems': 5203,
 'mayb': 4204,
 'yo': 7405,
 'howz': 3378,
 'girls': 3016,
 'never': 4547,
 'rang': 5336,
 'after': 818,
 'india': 3511,
 'discussed': 2259,
 'mother': 4392,
 'ah': 832,
 'fighting': 2732,
 'world': 7311,
 'easy': 2416,
 'either': 2447,
 'bt': 1493,
 'fightng': 2733,
 'some1': 6054,
 'dificult': 2224,
 'hear': 3228,
 'see': 5739,
 'sundayish': 6349,
 '0a': 237,
 'networks': 4544,
 'allow': 879,
 'companies': 1849,
 'bill': 1302,
 'responsible': 5504,
 'their': 6559,
 'suppliers': 6363,
 'give': 3019,
 'guarantee': 3127,
 'crazy': 1982,
 'great': 3105,
 'attracts': 1090,
 'brothas': 1478,
 'mum': 4439,
 'lookin': 4014,
 'strong': 6279,
 'okie': 4707,
 'fwiw': 2935,
 'reason': 5379,
 'smoke': 6014,
 'afford': 814,
 'tells': 6497,
 'apparently': 976,
 'happens': 3181,
 'somebody': 6055,
 'wants': 7102,
 'light': 3926,
 'very': 7000,
 'nice': 4564,
 'ready': 5367,
 'thursday': 6620,
 'askd': 1048,
 'before': 1250,
 'answer': 940,
 'dine': 2232,
 'lady': 3817,
 'freemsg': 2876,
 'hey': 3271,
 'darling': 2080,
 'been': 1244,
 'word': 7302,
 'fun': 2923,
 'tb': 6467,
 'xxx': 7364,
 'std': 6215,
 'chgs': 1711,
 'rcv': 5353,
 'winner': 7245,
 'specially': 6123,
 '1000': 241,
 'flights': 2790,
 'inc': 3495,
 'speak': 6118,
 'live': 3970,
 'operator': 4749,
 '0871277810910p': 110,
 '18': 303,
 'any': 950,
 'might': 4275,
 'evaporated': 2549,
 'violated': 7021,
 'privacy': 5192,
 'stealing': 6219,
 'employer': 2474,
 'paperwork': 4855,
 'cool': 1929,
 'report': 5479,
 'supervisor': 6361,
 'iouri': 3576,
 'gave': 2963,
 'wylie': 7350,
 'ryan': 5618,
 'friend': 2890,
 'convey': 1922,
 'best': 1279,
 'exam': 2587,
 'reunion': 5522,
 'probably': 5200,
 'pick': 4976,
 'boys': 1427,
 'problem': 5201,
 'granite': 3095,
 'issues': 3601,
 'explosive': 2623,
 'members': 4243,
 '300': 409,
 'nasdaq': 4491,
 'symbol': 6415,
 'cdgt': 1637,
 '00': 0,
 'per': 4926,
 'shopping': 5869,
 'them': 6561,
 'raining': 5321,
 'mah': 4125,
 'hard': 3187,
 'orchard': 4766,
 'free2day': 2870,
 'st': 6182,
 'george': 2990,
 'pic': 4975,
 'jordan': 3688,
 '89080': 685,
 'wk': 7269,
 'saucy': 5671,
 'celeb': 1641,
 'pics': 4979,
 'pocketbabe': 5059,
 'co': 1799,
 'uk': 6850,
 '0870241182716': 77,
 'course': 1961,
 'maths': 4192,
 'chapter': 1667,
 'month': 4376,
 'finish': 2754,
 'stupid': 6299,
 'possible': 5102,
 'inside': 3539,
 'outside': 4805,
 'bedroom': 1241,
 '09066649731from': 219,
 'await': 1121,
 'sae': 5628,
 'po': 5042,
 'box': 1409,
 '434': 471,
 'sk3': 5958,
 '8wp': 697,
 'hopeing': 3344,
 'wasn': 7111,
 'pissed': 4997,
 'remember': 5449,
 'gone': 3053,
 'off': 4680,
 'his': 3292,
 'sisters': 5946,
 'something': 6061,
 'hiya': 3300,
 'hav': 3205,
 'signal': 5917,
 'haven': 3209,
 'heard': 3229,
 'neither': 4533,
 'which': 7206,
 'unusual': 6913,
 'itself': 3610,
 'put': 5283,
 'case': 1616,
 'sort': 6088,
 'hugs': 3393,
 'snogs': 6032,
 'yetty': 7398,
 'smart': 6001,
 '200': 329,
 'weekly': 7159,
 'play': 5015,
 '85222': 659,
 'winnersclub': 7246,
 '84': 650,
 'm26': 4092,
 '3uz': 453,
 '16': 298,
 'gbp1': 2969,
 '447801259231': 476,
 'admirer': 791,
 'looking': 4015,
 'reveal': 5523,
 'thinks': 6586,
 'special': 6120,
 '09058094597': 173,
 'evening': 2553,
 'having': 3213,
 'bring': 1464,
 'notice': 4624,
 'late': 3845,
 'paying': 4905,
 'rent': 5464,
 'past': 4889,
 'months': 4379,
 'pay': 4900,
 'felt': 2712,
 'inconsiderate': 3503,
 'nag': 4473,
 'cost': 1943,
 'yourself': 7421,
 'why': 7219,
 'didnt': 2212,
 'however': 3375,
 'recession': 5396,
 'wont': 7294,
 'able': 728,
 'hence': 3258,
 'askin': 1050,
 'ahead': 834,
 'end': 2478,
 'everything': 2568,
 'smoking': 6018,
 'through': 6609,
 'difficult': 2223,
 'receipts': 5388,
 'done': 2316,
 'march': 4165,
 'truth': 6790,
 'against': 823,
 'gravity': 3100,
 'read': 5363,
 'carefully': 1603,
 'heart': 3231,
 'feels': 2707,
 'heavy': 3238,
 'leaves': 3879,
 'night': 4571,
 'tonite': 6706,
 'search': 5722,
 'opportunity': 4753,
 'went': 7177,
 'fast': 2680,
 'add': 780,
 'prayers': 5142,
 'double': 2328,
 'eviction': 2572,
 'spiral': 6144,
 'michael': 4271,
 'riddance': 5537,
 'sore': 6084,
 'throat': 6608,
 'scratches': 5709,
 'talk': 6441,
 'describe': 2171,
 'lucky': 4074,
 'actually': 777,
 'awake': 1123,
 'noon': 4602,
 'ringtone': 5545,
 'club': 1784,
 'gr8': 3083,
 'polys': 5076,
 'direct': 2241,
 'mobile': 4343,
 'rofl': 5563,
 'thats': 6552,
 'cover': 1965,
 'face': 2642,
 'hot': 3359,
 'sticky': 6231,
 'cum': 2033,
 'nooooooo': 4603,
 'bored': 1390,
 'death': 2109,
 'cable': 1543,
 'internet': 3557,
 'outage': 4795,
 'watch': 7117,
 'saw': 5678,
 'swatch': 6396,
 'thk': 6591,
 'quite': 5304,
 '116': 259,
 'opinion': 4750,
 'badrith': 1152,
 'chennai': 1705,
 'competition': 1854,
 'loved': 4044,
 'anyone': 954,
 'except': 2590,
 'gud': 3129,
 'nit': 4581,
 'andros': 922,
 'steal': 6218,
 'ice': 3434,
 'temales': 6501,
 'wonderful': 7291,
 '2waxsto': 402,
 'ill': 3465,
 'medical': 4226,
 'insurance': 3548,
 'deliver': 2147,
 'basic': 1191,
 'currently': 2038,
 'right': 5539,
 'til': 6633,
 'friday': 2886,
 'major': 4136,
 'guide': 3136,
 'dollars': 2310,
 'da': 2059,
 'days': 2094,
 'billion': 1305,
 'classes': 1759,
 'theoretically': 6567,
 'yeah': 7383,
 'write': 7329,
 'msg': 4413,
 'dictionary': 2208,
 'mode': 4354,
 'screen': 5714,
 'hand': 3166,
 'press': 5168,
 'remove': 5459,
 'interesting': 3554,
 'womdarfull': 7286,
 'actor': 775,
 'jst': 3695,
 'change': 1660,
 'tat': 6457,
 'busy': 1524,
 'year': 7384,
 'forward': 2851,
 'electricity': 2458,
 'fml': 2805,
 'actual': 776,
 'harder': 3189,
 'than': 6540,
 'nbme': 4507,
 'makes': 4138,
 'dearer': 2107,
 'de': 2099,
 'happiness': 3185,
 'pain': 4839,
 'dem': 2153,
 'polyphonic': 5075,
 'tone': 6697,
 'mob': 4341,
 'pt2': 5258,
 '87575': 675,
 '1st': 317,
 'free': 2869,
 'txtin': 6832,
 'friends': 2891,
 '150p': 289,
 'reply': 5477,
 'hl': 3301,
 '4info': 503,
 'thru': 6614,
 'different': 2222,
 'feeling': 2706,
 'wavering': 7129,
 'decisions': 2119,
 'coping': 1931,
 'same': 5648,
 'individual': 3515,
 'heal': 3225,
 'believe': 1263,
 'northampton': 4614,
 'afraid': 815,
 'staying': 6213,
 'skyving': 5971,
 'ho': 3310,
 'wednesday': 7151,
 'though': 6599,
 'fancy': 2671,
 'comedy': 1834,
 'hello': 3248,
 'baby': 1143,
 'mom': 4364,
 'setting': 5790,
 'computer': 1869,
 'filling': 2740,
 'goes': 3041,
 'loverboy': 4049,
 'sighs': 5914,
 'waaaat': 7069,
 'lololo': 4004,
 'next': 4560,
 'nationwide': 4499,
 'auto': 1105,
 'centre': 1647,
 'newport': 4554,
 'liked': 3931,
 'many': 4159,
 'dependents': 2164,
 'ic': 3432,
 'lotta': 4035,
 'childporn': 1720,
 'cars': 1613,
 'kicks': 3761,
 'definitely': 2134,
 'module': 4357,
 'humanities': 3397,
 'dis': 2247,
 'sem': 5761,
 'izzit': 3618,
 'wan': 7093,
 'other': 4785,
 'modules': 4358,
 'lovely': 4046,
 'smell': 6004,
 'ain': 842,
 'tobacco': 6672,
 'tonexs': 6701,
 'subscription': 6316,
 'renewed': 5462,
 'charged': 1671,
 'choose': 1735,
 'clubzed': 1789,
 'billing': 1304,
 'bath': 1199,
 'place': 5003,
 'key': 3750,
 'window': 7240,
 'ugh': 6847,
 'wanna': 7096,
 'bed': 1238,
 'warm': 7104,
 'bad': 1149,
 'girl': 3013,
 'registered': 5431,
 'subscribers': 6315,
 'enter': 2501,
 'draw': 2346,
 'gift': 3005,
 'voucher': 7052,
 'replying': 5478,
 'awarded': 1125,
 '2000': 330,
 'guaranteed': 3128,
 '09058094454': 167,
 'land': 3826,
 'line': 3940,
 '3030': 414,
 'valid': 6970,
 '12hrs': 273,
 'congratulations': 1894,
 've': 6986,
 'august': 1098,
 '09066660100': 220,
 '2309': 345,
 'happy': 3186,
 'guys': 3142,
 'asking': 1051,
 'slippers': 5988,
 'nope': 4605,
 'since': 5933,
 'ayo': 1134,
 'travelled': 6759,
 'forgotten': 2840,
 'guy': 3141,
 'cant': 1586,
 'awesome': 1127,
 'diesel': 2215,
 'subscribed': 6313,
 'content': 1910,
 'service': 5786,
 'ten': 6505,
 'until': 6912,
 '83435': 647,
 'helpline': 3256,
 '08706091795': 83,
 'yet': 7397,
 'chikku': 1717,
 'room': 5571,
 'nw': 4656,
 'nokia': 4592,
 'nok': 4591,
 '87021': 666,
 'top': 6717,
 ...}

Build Document-term Matrix (DTM)

In [ ]:
#Convert Training SMS messages into Count Vectors
X_train_ct = cvect.transform(sms_train)

In [ ]:
#Size of Document Term Matrix
X_train_ct.shape

(4179, 7450)

In [ ]:
#Let's check the first record
sms_train[0]

"Ok I'm gonna head up to usf in like fifteen minutes"

In [ ]:
# let's check first record
X_train_ct[0]

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10 stored elements and shape (1, 7450)>

In [ ]:
print(X_train_ct[0:1])

<Compressed Sparse Row sparse matrix of dtype 'int64'
	with 10 stored elements and shape (1, 7450)>
  Coords	Values
  (0, 2729)	1
  (0, 3055)	1
  (0, 3219)	1
  (0, 3493)	1
  (0, 3930)	1
  (0, 4301)	1
  (0, 4703)	1
  (0, 6669)	1
  (0, 6914)	1
  (0, 6950)	1

In [ ]:
X_test_ct = cvect.transform(sms_test)
X_test_ct.shape

(1393, 7450)

## 4. Building an SMS Classifier

Building an SMS Classifier

In [ ]:
from sklearn.neighbors import KNeighborsClassifier

In [ ]:
#instantiate the model (with the default parameters)
knn = KNeighborsClassifier()
# fit the model with data (occurs in-place)
knn.fit(X_train_ct, y_train)

KNeighborsClassifier()

Evaluation on Test Dataset

In [ ]:
from sklearn import metrics
#Calculate accuracy on Test Dataset
metrics.accuracy_score (y_test, knn.predict(X_test_ct))

0.908829863603733

In [ ]:
#Calculate accuracy on Training Dataset
metrics.accuracy_score(y_train, knn.predict(X_train_ct))

0.931323283082077

### We can build Classifier using other algorithms e.g SVM

In [ ]:
from sklearn.svm import SVC

In [ ]:
#Train an SVM with default parameters
Svc = SVC()
Svc.fit (X_train_ct, y_train)

SVC()

In [ ]:
#Calculate accuracy on Test Dataset
metrics.accuracy_score(y_test, Svc.predict(X_test_ct))

0.9734386216798278

In [ ]:
#Calculate accuracy on Train Dataset
metrics.accuracy_score(y_train, Svc.predict(X_train_ct))

0.9961713328547499

###   RandomForestClassifier

In [ ]:
from sklearn.ensemble import RandomForestClassifier

In [ ]:
rf_model = RandomForestClassifier()
rf_model.fit(X_train_ct, y_train)

RandomForestClassifier()

In [ ]:
#Calculate accuracy on Test Dataset
metrics.accuracy_score (y_test, rf_model.predict(X_test_ct))

0.9748743718592965

In [ ]:
#Calculate accuracy on Train Dataset
metrics.accuracy_score (y_train, rf_model.predict(X_train_ct))

1.0

## 5. Using TF-IDF Vectorizer

In [ ]:
# import and instantiate TF-IDF Vectorizer (with the default parameters)
from sklearn.feature_extraction.text import TfidfVectorizer

In [ ]:
tvect = TfidfVectorizer()

In [ ]:
#Feed SMS data to CountVectorizer
tvect.fit(sms_train)

TfidfVectorizer()

In [ ]:
#Check the vocablury size
len(tvect.vocabulary_)

7450

In [ ]:
#Convert Training SMS messages into numerical values
X_train_tfidf = tvect.transform(sms_train)

In [ ]:
X_train_tfidf.shape

(4179, 7450)

In [ ]:
#Check first example
print(X_train_tfidf[0])

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 10 stored elements and shape (1, 7450)>
  Coords	Values
  (0, 2729)	0.4559918073186443
  (0, 3055)	0.32903708027650574
  (0, 3219)	0.39961629588650566
  (0, 3493)	0.17274663708337384
  (0, 3930)	0.24622502082036948
  (0, 4301)	0.3587203683649993
  (0, 4703)	0.23805235497155508
  (0, 6669)	0.1289628315241441
  (0, 6914)	0.23272328753423327
  (0, 6950)	0.4213121872897114

In [ ]:
#Convert Test SMSes also to tf-idf vectors
X_test_tfidf = tvect.transform (sms_test)

###     RandomForestClassifier

In [ ]:
rf_model_tf = RandomForestClassifier()
rf_model_tf.fit(X_train_tfidf, y_train)

RandomForestClassifier()

In [ ]:
#Calculate accuracy on Test Dataset
metrics.accuracy_score(y_test, rf_model_tf.predict(X_test_tfidf))

0.9763101220387652

## 6. TF-IDF With ngram

In [ ]:
#Use ngrams of length upto 2 words
tvect_ngram = TfidfVectorizer (ngram_range=(1,2)) #Tokens can be made of 1 word or 2 words

In [ ]:
#sms_df.head()
#Feed SMS data to CountVectorizer
tvect_ngram.fit(sms_df.message)

TfidfVectorizer(ngram_range=(1, 2))

In [ ]:
#Check the vocablury size
len(tvect_ngram. vocabulary_)

50506

The movie was awesome

Words as tokens = "The", "movie", "was", awesome"
ngrams (1,2) -> "The", "movie", "was", awesome", "The movie", "movie was", "was awesome"

In [ ]:
tvect_ngram.vocabulary_

{'go': 17053,
 'until': 45043,
 'jurong': 22942,
 'point': 33486,
 'crazy': 10745,
 'available': 5424,
 'only': 31320,
 'in': 21062,
 'bugis': 7589,
 'great': 17791,
 'world': 48749,
 'la': 23682,
 'buffet': 7584,
 'cine': 9510,
 'there': 42067,
 'got': 17535,
 'amore': 3446,
 'wat': 46559,
 'go until': 17168,
 'until jurong': 45051,
 'jurong point': 22943,
 'point crazy': 33489,
 'crazy available': 10748,
 'available only': 5433,
 'only in': 31375,
 'in bugis': 21112,
 'bugis great': 7591,
 'great world': 17853,
 'world la': 48759,
 'la buffet': 23683,
 'buffet cine': 7585,
 'cine there': 9517,
 'there got': 42108,
 'got amore': 17542,
 'amore wat': 3447,
 'ok': 30728,
 'lar': 23792,
 'joking': 22860,
 'wif': 47844,
 'oni': 31291,
 'ok lar': 30779,
 'lar joking': 23802,
 'joking wif': 22863,
 'wif oni': 47856,
 'free': 15745,
 'entry': 13783,
 'wkly': 48447,
 'comp': 10103,
 'to': 43120,
 'win': 48057,
 'fa': 14340,
 'cup': 10926,
 'final': 14838,
 'tkts': 43074,
 '21st': 988,
 'may': 26127,
 '2005': 964,
 'text': 40670,
 '87121': 1937,
 'receive': 34921,
 'question': 34357,
 'std': 39252,
 'txt': 44648,
 'rate': 34556,
 'apply': 4463,
 '08452810075over18': 178,
 'free entry': 15778,
 'entry in': 13785,
 'in wkly': 21403,
 'wkly comp': 48448,
 'comp to': 10109,
 'to win': 43722,
 'win fa': 48067,
 'fa cup': 14341,
 'cup final': 10928,
 'final tkts': 14845,
 'tkts 21st': 43075,
 '21st may': 990,
 'may 2005': 26128,
 '2005 text': 965,
 'text fa': 40688,
 'fa to': 14342,
 'to 87121': 43190,
 '87121 to': 1939,
 'to receive': 43562,
 'receive entry': 34933,
 'entry question': 13788,
 'question std': 34366,
 'std txt': 39256,
 'txt rate': 44694,
 'rate apply': 34558,
 'apply 08452810075over18': 4465,
 'dun': 13165,
 'say': 36205,
 'so': 38126,
 'early': 13272,
 'hor': 20208,
 'already': 3100,
 'then': 41938,
 'dun say': 13182,
 'say so': 36253,
 'so early': 38177,
 'early hor': 13278,
 'hor already': 20209,
 'already then': 3140,
 'then say': 42019,
 'nah': 28473,
 'don': 12623,
 'think': 42359,
 'he': 19013,
 'goes': 17223,
 'usf': 45590,
 'lives': 24764,
 'around': 4787,
 'here': 19456,
 'though': 42662,
 'nah don': 28475,
 'don think': 12676,
 'think he': 42376,
 'he goes': 19052,
 'goes to': 17230,
 'to usf': 43702,
 'usf he': 45593,
 'he lives': 19077,
 'lives around': 24765,
 'around here': 4801,
 'here though': 19513,
 'freemsg': 15880,
 'hey': 19546,
 'darling': 11224,
 'it': 22150,
 'been': 6342,
 'week': 46967,
 'now': 29818,
 'and': 3594,
 'no': 29173,
 'word': 48612,
 'back': 5692,
 'like': 24453,
 'some': 38370,
 'fun': 16325,
 'you': 49557,
 'up': 45068,
 'for': 15284,
 'still': 39306,
 'tb': 40405,
 'xxx': 49112,
 'chgs': 9365,
 'send': 36684,
 '50': 1490,
 'rcv': 34596,
 'freemsg hey': 15885,
 'hey there': 19611,
 'there darling': 42095,
 'darling it': 11227,
 'it been': 22177,
 'been week': 6414,
 'week now': 47007,
 'now and': 29847,
 'and no': 3873,
 'no word': 29361,
 'word back': 48615,
 'back like': 5728,
 'like some': 24549,
 'some fun': 38394,
 'fun you': 16346,
 'you up': 49993,
 'up for': 45104,
 'for it': 15419,
 'it still': 22369,
 'still tb': 39387,
 'tb ok': 40408,
 'ok xxx': 30842,
 'xxx std': 49118,
 'std chgs': 39253,
 'chgs to': 9366,
 'to send': 43608,
 'send 50': 36685,
 '50 to': 1513,
 'to rcv': 43557,
 'even': 13929,
 'my': 28104,
 'brother': 7485,
 'is': 21761,
 'not': 29517,
 'speak': 38844,
 'with': 48200,
 'me': 26199,
 'they': 42203,
 'treat': 44356,
 'aids': 2772,
 'patent': 32553,
 'even my': 13956,
 'my brother': 28144,
 'brother is': 7490,
 'is not': 21963,
 'not like': 29645,
 'like to': 24563,
 'to speak': 43633,
 'speak with': 38854,
 'with me': 48293,
 'me they': 26427,
 'they treat': 42264,
 'treat me': 44360,
 'me like': 26340,
 'like aids': 24456,
 'aids patent': 2773,
 'as': 4870,
 'per': 32700,
 'your': 50054,
 'request': 35322,
 'melle': 26666,
 'oru': 31842,
 'minnaminunginte': 26980,
 'nurungu': 30120,
 'vettam': 45846,
 'has': 18629,
 'set': 36894,
 'callertune': 8400,
 'all': 2919,
 'callers': 8398,
 'press': 33846,
 'copy': 10459,
 'friends': 15988,
 'as per': 4922,
 'per your': 32717,
 'your request': 50288,
 'request melle': 35326,
 'melle melle': 26667,
 'melle oru': 26668,
 'oru minnaminunginte': 31843,
 'minnaminunginte nurungu': 26981,
 'nurungu vettam': 30121,
 'vettam has': 45847,
 'has been': 18634,
 'been set': 6391,
 'set as': 36895,
 'as your': 4960,
 'your callertune': 50099,
 'callertune for': 8401,
 'for all': 15311,
 'all callers': 2933,
 'callers press': 8399,
 'press to': 33852,
 'to copy': 43303,
 'copy your': 10464,
 'your friends': 50157,
 'friends callertune': 15995,
 'winner': 48112,
 'valued': 45683,
 'network': 28789,
 'customer': 10967,
 'have': 18739,
 'selected': 36624,
 'receivea': 34941,
 '900': 2017,
 'prize': 33966,
 'reward': 35458,
 'claim': 9534,
 'call': 8118,
 '09061701461': 446,
 'code': 9785,
 'kl341': 23474,
 'valid': 45667,
 '12': 694,
 'hours': 20296,
 'winner as': 48113,
 'as valued': 4952,
 'valued network': 45688,
 'network customer': 28794,
 'customer you': 10980,
 'you have': 49726,
 'have been': 18761,
 'been selected': 6388,
 'selected to': 36628,
 'to receivea': 43563,
 'receivea 900': 34942,
 '900 prize': 2019,
 'prize reward': 33982,
 'reward to': 35463,
 'to claim': 43284,
 'claim call': 9545,
 'call 09061701461': 8215,
 '09061701461 claim': 447,
 'claim code': 9548,
 'code kl341': 9805,
 'kl341 valid': 23475,
 'valid 12': 45668,
 '12 hours': 699,
 'hours only': 20302,
 'had': 18259,
 'mobile': 27227,
 '11': 663,
 'months': 27495,
 'or': 31540,
 'more': 27517,
 'entitled': 13778,
 'update': 45199,
 'the': 41209,
 'latest': 23954,
 'colour': 9890,
 'mobiles': 27282,
 'camera': 8470,
 'co': 9757,
 'on': 30938,
 '08002986030': 148,
 'had your': 18312,
 'your mobile': 50224,
 'mobile 11': 27230,
 '11 months': 668,
 'months or': 27501,
 'or more': 31661,
 'more entitled': 27531,
 'entitled to': 13779,
 'to update': 43696,
 'update to': 45205,
 'to the': 43666,
 'the latest': 41504,
 'latest colour': 23956,
 'colour mobiles': 9894,
 'mobiles with': 27288,
 'with camera': 48232,
 'camera for': 8472,
 'for free': 15387,
 'free call': 15762,
 'call the': 8334,
 'the mobile': 41556,
 'mobile update': 27274,
 'update co': 45200,
 'co free': 9759,
 'free on': 15818,
 'on 08002986030': 30949,
 'gonna': 17340,
 'be': 6034,
 'home': 20008,
 'soon': 38619,
 'want': 46285,
 'talk': 40296,
 'about': 2112,
 'this': 42445,
 'stuff': 39655,
 'anymore': 4300,
 'tonight': 44008,
 've': 45722,
 'cried': 10809,
 'enough': 13733,
 'today': 43754,
 'gonna be': 17342,
 'be home': 6107,
 'home soon': 20075,
 'soon and': 38621,
 'and don': 3702,
 'don want': 12683,
 'want to': 46331,
 'to talk': 43653,
 'talk about': 40297,
 'about this': 2178,
 'this stuff': 42544,
 'stuff anymore': 39657,
 'anymore tonight': 4304,
 'tonight ve': 44028,
 've cried': 45729,
 'cried enough': 10810,
 'enough today': 13747,
 'six': 37741,
 'chances': 9109,
 'cash': 8915,
 'from': 16091,
 '100': 606,
 '20': 932,
 '000': 5,
 'pounds': 33685,
 'csh11': 10865,
 '87575': 1952,
 'cost': 10544,
 '150p': 767,
 'day': 11316,
 '6days': 1690,
 '16': 818,
 'tsandcs': 44512,
 'reply': 35250,
 'hl': 19888,
 'info': 21510,
 'six chances': 37742,
 'chances to': 9110,
 'win cash': 48066,
 'cash from': 8923,
 'from 100': 16093,
 '100 to': 615,
 'to 20': 43124,
 '20 000': 933,
 '000 pounds': 9,
 'pounds txt': 33693,
 'txt csh11': 44663,
 'csh11 and': 10866,
 'and send': 3941,
 'send to': 36739,
 'to 87575': 43193,
 '87575 cost': 1954,
 'cost 150p': 10547,
 '150p day': 771,
 'day 6days': 11318,
 '6days 16': 1691,
 '16 tsandcs': 833,
 'tsandcs apply': 44513,
 'apply reply': 4473,
 'reply hl': 35262,
 'hl info': 19890,
 'urgent': 45440,
 'won': 48494,
 'membership': 26682,
 'our': 31939,
 'jackpot': 22629,
 '81010': 1822,
 'www': 49004,
 'dbuk': 11454,
 'net': 28765,
 'lccltd': 24021,
 'pobox': 33441,
 '4403ldnw1a7rw18': 1382,
 'urgent you': 45454,
 'have won': 18927,
 'won week': 48528,
 'week free': 46991,
 'free membership': 15801,
 'membership in': 26683,
 'in our': 21294,
 'our 100': 31940,
 '100 000': 607,
 '000 prize': 11,
 'prize jackpot': 33976,
 'jackpot txt': 22630,
 'txt the': 44703,
 'the word': 41835,
 'word claim': 48618,
 'claim to': 9562,
 'to no': 43506,
 'no 81010': 29184,
 '81010 www': 1823,
 'www dbuk': 49020,
 'dbuk net': 11455,
 'net lccltd': 28772,
 'lccltd pobox': 24022,
 'pobox 4403ldnw1a7rw18': 33445,
 'searching': 36458,
 'right': 35495,
 'words': 48632,
 'thank': 40854,
 'breather': 7387,
 'promise': 34125,
 'wont': 48569,
 'take': 40194,
 'help': 19330,
 'granted': 17769,
 'will': 47908,
 'fulfil': 16304,
 'wonderful': 48545,
 'blessing': 6931,
 'at': 5129,
 'times': 42997,
 've been': 45725,
 'been searching': 6386,
 'searching for': 36459,
 'for the': 15525,
 'the right': 41679,
 'right words': 35527,
 'words to': 48645,
 'to thank': 43664,
 'thank you': 40858,
 'you for': 49694,
 'for this': 15529,
 'this breather': 42454,
 'breather promise': 7388,
 'promise wont': 34130,
 'wont take': 48590,
 'take your': 40251,
 'your help': 50182,
 'help for': 19338,
 'for granted': 15403,
 'granted and': 17770,
 'and will': 4061,
 'will fulfil': 47949,
 'fulfil my': 16305,
 'my promise': 28342,
 'promise you': 34131,
 'been wonderful': 6416,
 'wonderful and': 48546,
 'and blessing': 3639,
 'blessing at': 6932,
 'at all': 5155,
 'all times': 3021,
 'date': 11282,
 'sunday': 39872,
 'have date': 18779,
 'date on': 11291,
 'on sunday': 31101,
 'sunday with': 39878,
 'with will': 48363,
 'xxxmobilemovieclub': 49119,
 'use': 45534,
 'credit': 10774,
 'click': 9654,
 'wap': 46366,
 'link': 24648,
 'next': 28961,
 'message': 26730,
 'http': 20484,
 'com': 9905,
 'qjkgighjjgcbl': 34334,
 'xxxmobilemovieclub to': 49121,
 'to use': 43700,
 'use your': 45563,
 'your credit': 50118,
 'credit click': 10778,
 'click the': 9660,
 'the wap': 41813,
 'wap link': 46370,
 'link in': 24649,
 'in the': 21363,
 'the next': 41576,
 'next txt': 28991,
 'txt message': 44677,
 'message or': 26755,
 'or click': 31587,
 'click here': 9657,
 'here http': 19485,
 'http wap': 20491,
 'wap xxxmobilemovieclub': 46374,
 'xxxmobilemovieclub com': 49120,
 'com qjkgighjjgcbl': 9925,
 'oh': 30648,
 'watching': 46639,
 'oh watching': 30704,
 'watching here': 46648,
 'eh': 13471,
 'remember': 35136,
 'how': 20337,
 'spell': 38908,
 'his': 19808,
 'name': 28497,
 'yes': 49362,
 'did': 11906,
 'naughty': 28581,
 'make': 25766,
 'wet': 47302,
 'eh remember': 13474,
 'remember how': 35141,
 'how spell': 20408,
 'spell his': 38909,
 'his name': 19835,
 'name yes': 28518,
 'yes did': 49377,
 'did he': 11928,
 'he naughty': 19087,
 'naughty make': 28585,
 'make until': 25806,
 'until wet': 45063,
 'fine': 14905,
 'if': 20729,
 'that': 40917,
 'way': 46695,
 'feel': 14610,
 'its': 22448,
 'gota': 17684,
 'fine if': 14924,
 'if that': 20814,
 'that the': 41137,
 'the way': 41817,
 'way feel': 46704,
 'feel that': 14634,
 'way its': 46714,
 'its gota': 22484,
 'england': 13684,
 'macedonia': 25638,
 'dont': 12730,
 'miss': 27057,
 'goals': 17187,
 'team': 40450,
 'news': 28941,
 'ur': 45243,
 'national': 28565,
 '87077': 1931,
 'eg': 13451,
 'try': 44476,
 'wales': 46168,
 'scotland': 36389,
 '4txt': 1468,
 'ú1': 50502,
 'poboxox36504w45wq': 33469,
 'england macedonia': 13687,
 'macedonia dont': 25639,
 'dont miss': 12769,
 'miss the': 27079,
 'the goals': 41434,
 'goals team': 17189,
 'team news': 40454,
 'news txt': 28953,
 'txt ur': 44706,
 'ur national': 45363,
 'national team': 28568,
 'team to': 40456,
 'to 87077': 43189,
 '87077 eg': 1932,
 'eg england': 13452,
 'england to': 13689,
 '87077 try': 1935,
 'try wales': 44498,
 'wales scotland': 46171,
 'scotland 4txt': 36390,
 '4txt ú1': 1470,
 'ú1 20': 50503,
 '20 poboxox36504w45wq': 939,
 'poboxox36504w45wq 16': 33470,
 'seriously': 36842,
 'is that': 22051,
 'that seriously': 41112,
 'seriously how': 36846,
 'how you': 20428,
 'you spell': 49932,
 'going': 17257,
 'ha': 18240,
 'going to': 17299,
 'to try': 43690,
 'try for': 44482,
 'for months': 15451,
 'months ha': 27499,
 'ha ha': 18244,
 'ha only': 18248,
 'only joking': 31379,
 'pay': 32578,
 'first': 15019,
 'when': 47432,
 'da': 11032,
 'stock': 39406,
 'comin': 10050,
 'so pay': 38253,
 'pay first': 32583,
 'first lar': 15033,
 'lar then': 23813,
 'then when': 42049,
 'when is': 47474,
 'is da': 21842,
 'da stock': 11106,
 'stock comin': 39407,
 'aft': 2528,
 'finish': 14951,
 'lunch': 25509,
 'str': 39540,
 'down': 12857,
 'lor': 25113,
 'ard': 4545,
 'smth': 38067,
 'aft finish': 2533,
 'finish my': 14966,
 'my lunch': 28285,
 'lunch then': 25530,
 'then go': 41972,
 'go str': 17149,
 'str down': 39542,
 'down lor': 12870,
 'lor ard': 25118,
 'ard smth': 4560,
 'smth lor': 38074,
 'lor finish': 25133,
 'finish ur': 14972,
 'ur lunch': 45346,
 'lunch already': 25513,
 'ffffffffff': 14750,
 'alright': 3157,
 'can': 8492,
 'meet': 26577,
 'sooner': 38648,
 'ffffffffff alright': 14751,
 'alright no': 3164,
 'no way': 29356,
 'way can': 46699,
 'can meet': 8582,
 'meet up': 26612,
 'up with': 45183,
 'with you': 48367,
 'you sooner': 49927,
 'just': 22973,
 'forced': 15580,
 'myself': 28442,
 'eat': 13341,
 'slice': 37868,
 'really': 34801,
 'hungry': 20550,
 'tho': 42622,
 'sucks': 39780,
 'mark': 25993,
 'getting': 16835,
 'worried': 48780,
 'knows': 23611,
 'sick': 37499,
 'turn': 44561,
 'pizza': 33088,
 'lol': 24949,
 'just forced': 23031,
 'forced myself': 15581,
 'myself to': 28449,
 'to eat': 43341,
 'eat slice': 13362,
 'slice really': 37870,
 'really not': 34845,
 'not hungry': 29625,
 'hungry tho': 20556,
 'tho this': 42630,
 'this sucks': 42545,
 'sucks mark': 39784,
 'mark is': 25995,
 'is getting': 21886,
 'getting worried': 16871,
 'worried he': 48782,
 'he knows': 19074,
 'knows sick': 23615,
 'sick when': 37505,
 'when turn': 47524,
 'turn down': 44563,
 'down pizza': 12876,
 'pizza lol': 33092,
 'always': 3260,
 'convincing': 10400,
 'lol your': 24992,
 'your always': 50072,
 'always so': 3291,
 'so convincing': 38162,
 'catch': 8960,
 'bus': 7644,
 'are': 4563,
 'frying': 16243,
 'an': 3520,
 'egg': 13462,
 'tea': 40425,
 'eating': 13384,
 'mom': 27341,
 'left': 24143,
 'over': 32185,
 'dinner': 12125,
 'do': 12312,
 'love': 25279,
 'did you': 11973,
 'you catch': 49629,
 'catch the': 8963,
 'the bus': 41293,
 'bus are': 7646,
 'are you': 4713,
 'you frying': 49700,
 'frying an': 16244,
 'an egg': 3545,
 'egg did': 13463,
 'you make': 49785,
 'make tea': 25799,
 'tea are': 40427,
 'you eating': 49672,
 'eating your': 13390,
 'your mom': 50225,
 'mom left': 27351,
 'left over': 24163,
 'over dinner': 32200,
 'dinner do': 12132,
 'do you': 12427,
 'you feel': 49687,
 'feel my': 14627,
 'my love': 28283,
 'amp': 3452,
 'we': 46751,
 're': 34610,
 'packing': 32312,
 'car': 8755,
 'll': 24778,
 'let': 24269,
 'know': 23501,
 'room': 35689,
 'back amp': 5695,
 'amp we': 3501,
 'we re': 46844,
 're packing': 34649,
 'packing the': 32313,
 'the car': 41300,
 'car now': 8771,
 'now ll': 29929,
 'll let': 24824,
 'let you': 24289,
 'you know': 49757,
 'know if': 23542,
 'if there': 20817,
 'there room': 42139,
 'ahhh': 2758,
 'work': 48646,
 'vaguely': 45651,
 'what': 47309,
 'does': 12459,
 'ahhh work': 2759,
 'work vaguely': 48703,
 'vaguely remember': 45652,
 'remember that': 35148,
 'that what': 41162,
 'what does': 47326,
 'does it': 12470,
 'it feel': 22228,
 'feel like': 14624,
 'like lol': 24509,
 'wait': 46105,
 'clear': 9637,
 'were': 47234,
 'sure': 39957,
 'being': 6504,
 'sarcastic': 36098,
 'why': 47780,
 'doesn': 12482,
 'live': 24738,
 'us': 45487,
 'wait that': 46129,
 'that still': 41127,
 'still not': 39366,
 'not all': 29523,
 'all that': 3011,
 'that clear': 40960,
 'clear were': 9640,
 'were you': 47280,
 'you not': 49821,
 'not sure': 29716,
 'sure about': 39958,
 'about me': 2156,
 'me being': 26243,
 'being sarcastic': 6530,
 'sarcastic or': 36099,
 'or that': 31717,
 'that that': 41135,
 'that why': 41165,
 'why doesn': 47794,
 'doesn want': 12499,
 'to live': 43461,
 'live with': 24756,
 'with us': 48354,
 'yeah': 49227,
 'was': 46397,
 'apologetic': 4432,
 'fallen': 14428,
 'out': 32023,
 'she': 37062,
 'actin': 2336,
 'spoilt': 38983,
 'child': 9399,
 'caught': 8973,
 'till': 42870,
 'but': 7690,
 'doing': 12550,
 'too': 44049,
 'badly': 5798,
 'cheers': 9319,
 'yeah he': 49244,
 'he got': 19055,
 'got in': 17590,
 'in at': 21097,
 'at and': 5159,
 'and was': 4044,
 'was apologetic': 46404,
 'apologetic had': 4433,
 'had fallen': 18273,
 'fallen out': 14429,
 'out and': 32031,
 'and she': 3945,
 'she was': 37147,
 'was actin': 46400,
 'actin like': 2337,
 'like spoilt': 24551,
 'spoilt child': 38984,
 'child and': 9400,
 'and he': 3782,
 'got caught': 17559,
 'caught up': 8975,
 'up in': 45117,
 'in that': 21362,
 'that till': 41143,
 'till but': 42874,
 'but we': 7869,
 'we won': 46884,
 'won go': 48516,
 'go there': 17159,
 'there not': 42127,
 'not doing': 29578,
 'doing too': 12590,
 'too badly': 44054,
 'badly cheers': 5799,
 'cheers you': 9324,
 'tell': 40508,
 'anything': 4328,
 'tell me': 40525,
 'me anything': 26222,
 'anything about': 4329,
 'about you': 2192,
 'fear': 14588,
 'of': 30222,
 'fainting': 14407,
 'housework': 20333,
 'quick': 34379,
 'cuppa': 10933,
 'for fear': 15380,
 'fear of': 14590,
 'of fainting': 30297,
 'fainting with': 14408,
 'with the': 48343,
 'the of': 41587,
 'of all': 30230,
 'that housework': 41023,
 'housework you': 20334,
 'you just': 49753,
 'just did': 23017,
 'did quick': 11947,
 'quick have': 34382,
 'have cuppa': 18778,
 'thanks': 40860,
 'subscription': 39755,
 'ringtone': 35558,
 'uk': 44806,
 'charged': 9168,
 'month': 27461,
 'please': 33250,
 'confirm': 10238,
 'by': 7970,
 'replying': 35304,
 'thanks for': 40866,
 'for your': 15573,
 'your subscription': 50314,
 'subscription to': 39760,
 'to ringtone': 43585,
 'ringtone uk': 35574,
 'uk your': 44846,
 'mobile will': 27279,
 'will be': 47914,
 'be charged': 6065,
 'charged month': 9174,
 'month please': 27483,
 'please confirm': 33259,
 'confirm by': 10240,
 'by replying': 8038,
 'replying yes': 35311,
 'yes or': 49401,
 'or no': 31671,
 'no if': 29259,
 'if you': 20841,
 'you reply': 49876,
 'reply no': 35275,
 'no you': 29365,
 'you will': 50026,
 'will not': 47992,
 'not be': 29539,
 'yup': 50439,
 'look': 25048,
 'timings': 43025,
 'msg': 27788,
 'again': 2633,
 'xuhui': 49100,
 'learn': 24056,
 '2nd': 1139,
 'her': 19381,
 'lesson': 24243,
 '8am': 1998,
 'yup ok': 50462,
 'ok go': 30760,
 'go home': 17101,
 'home look': 20056,
 'look at': 25050,
 'at the': 5279,
 'the timings': 41777,
 'timings then': 43026,
 'then msg': 42004,
 'msg again': 27794,
 'again xuhui': 2672,
 'xuhui going': 49102,
 'to learn': 43452,
 'learn on': 24059,
 'on 2nd': 30974,
 '2nd may': 1142,
 'may too': 26149,
 'too but': 44057,
 'but her': 7755,
 'her lesson': 19414,
 'lesson is': 24251,
 'is at': 21797,
 'at 8am': 5149,
 'oops': 31462,
 'roommate': 35715,
 'done': 12692,
 'oops ll': 31466,
 'know when': 23589,
 'when my': 47491,
 'my roommate': 28356,
 'roommate done': 35717,
 'see': 36520,
 'letter': 24307,
 'see the': 36555,
 'the letter': 41515,
 'letter on': 24309,
 'on my': 31069,
 'my car': 28151,
 'decide': 11580,
 'anything lor': 4350,
 ...}

In [ ]:
#Convert Training SMS messages into numerical values
X_train_tfidf_ngram = tvect_ngram.transform(sms_train)

In [ ]:
X_train_tfidf_ngram.shape

(4179, 50506)

In [ ]:
rf_model_tf_ngram = RandomForestClassifier()
rf_model_tf_ngram.fit(X_train_tfidf_ngram, y_train)

RandomForestClassifier()

In [ ]:
#Calculate accuracy on Test Dataset
metrics.accuracy_score (y_test, rf_model_tf_ngram.predict(tvect_ngram.transform(sms_test)))

0.9705671213208902

In [ ]:
#Calculate accuracy on Train Dataset
metrics.accuracy_score (y_train, rf_model_tf_ngram.predict(X_train_tfidf_ngram))

1.0


### Summary:
1)vect.fit(train) learns the **vocabulary** of the training data.

2) vect.transform(train) uses the **fitted vocabulary** to build a **document-term matrix** from the training data.

3) vect.transform(test) uses the **fitted vocabulary** to build a document-term matrix from the testing data and **ignores tokens** it hasn't seen before.

## 7. Building a Deep Learning Model

In [ ]:
import tensorflow as tf

We will use CountVectorizer features in this case. This can be replaced by TF-IDF features

In [ ]:
#Start building a Keras Sequential Model
tf.keras.backend.clear_session()
model = tf.keras. Sequential()

In [ ]:
#Add hidden layers
model.add(tf.keras.layers. Dense (100, activation='relu', input_shape=(len(tvect.vocabulary_),)))
model.add(tf.keras.layers. Dropout (0.4))
model.add(tf.keras.layers.Dense (50, activation='relu'))
model.add(tf.keras.layers. Dropout (0.4))

#Add Output layer
model.add(tf.keras.layers. Dense (1, activation='sigmoid'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:93: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
#Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 100)            │       745,100 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout (Dropout)               │ (None, 100)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 50)             │         5,050 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dropout_1 (Dropout)             │ (None, 50)             │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 1)              │            51 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 750,201 (2.86 MB)

 Trainable params: 750,201 (2.86 MB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
X_train_ct.shape

(4179, 7450)

In [ ]:
model.fit(X_train_ct.todense(),
          y_train, validation_data=(X_test_ct.todense(), y_test),
          epochs=10, batch_size=32)

Epoch 1/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 4s 16ms/step - accuracy: 0.8498 - loss: 0.4160 - val_accuracy: 0.9756 - val_loss: 0.0974
Epoch 2/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9935 - loss: 0.0389 - val_accuracy: 0.9799 - val_loss: 0.0914
Epoch 3/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 3s 20ms/step - accuracy: 0.9972 - loss: 0.0133 - val_accuracy: 0.9806 - val_loss: 0.1009
Epoch 4/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 2s 16ms/step - accuracy: 0.9992 - loss: 0.0052 - val_accuracy: 0.9792 - val_loss: 0.1267
Epoch 5/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 2s 15ms/step - accuracy: 0.9995 - loss: 0.0028 - val_accuracy: 0.9799 - val_loss: 0.1318
Epoch 6/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.9999 - loss: 0.0014 - val_accuracy: 0.9799 - val_loss: 0.1477
Epoch 7/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 3s 15ms/step - accuracy: 0.9992 - loss: 0.0021 - val_accuracy: 0.9792 - val_loss: 0.1616
Epoch 8/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 2s 17ms/step - accuracy: 0.9999 - loss: 8.4793e-04 - val_accuracy: 0.9799 - val_loss: 0.1574
Epoch 9/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 3s 17ms/step - accuracy: 0.9998 - loss: 0.0011 - val_accuracy: 0.9785 - val_loss: 0.1430
Epoch 10/10
131/131 ━━━━━━━━━━━━━━━━━━━━ 2s 13ms/step - accuracy: 0.9997 - loss: 9.1182e-04 - val_accuracy: 0.9792 - val_loss: 0.1640

In [ ]:
X_train_ct.todense()[0]

In [ ]:
print(X_train_ct[0])

In [ ]:
#Start building a Keras Sequential Model
tf.keras.backend.clear_session()
model=tf.keras.Sequential()

#Add hidden layers
model.add(tf.keras.layers. Reshape((7450,1), input_shape=(len(tvect.vocabulary_),)))
model.add(tf.keras.layers. Conv1D (100, kernel_size=(3), activation='relu'))
model.add(tf.keras.layers. Dropout (0.4))
model.add(tf.keras.layers. Conv1D (50, kernel_size=(3), activation='relu'))
model.add(tf.keras.layers. Dropout (0.4))

model.add(tf.keras.layers.Flatten())
#Add Output layer
model.add(tf.keras.layers. Dense (1, activation='sigmoid'))

#Compile the model
model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
model.fit(X_train_ct.todense(),y_train,
          validation_data=(X_test_ct.todense(), y_test),
          epochs=1, batch_size=32)

In [ ]:
model.summary()

### 8.Controlling Vocabulary Size

Thus far, we have been using the default parameter of CountVectorizer

In [ ]:
cvect.vocabulary_

In [ ]:
#?cvect

**max_df**: float in range [0.0, 1.0] or int, default=1.0

• When building the vocabulary, ignore terms that have a document frequency strictly higher than the given threshold (corpus-specific stop words).
o If float, the parameter represents a proportion of documents.
• If integer, the parameter represents an absolute count.

In [ ]:
# ignore terms that appear in more than 50% of the documents
vect = CountVectorizer(max_df=0.1)
vect.fit(sms_train)
len(vect.get_feature_names_out())

   min_df: int, default=1

In [ ]:
# only keep terms that apper in at least 2 documents
vect=CountVectorizer(min_df=2)
vect.fit(sms_train)
len(vect.get_feature_names_out())

In [ ]:
vect.vocabulary_